### ISSUE TITLE
withHadrianDeps no longer works

### ISSUE THREAD

**Issue by TerrorJack** [alpmestan/ghc.nix#113]
For a recent ghc-head checkout, setting `withHadrianDeps = true` will still result in the building of various hadrian dependency packages if they aren't built already in the cabal store.

**Comment by supersven** [comment]
Hey @TerrorJack ,

Could you please check if this PR/branch solves this issue: https://github.com/alpmestan/ghc.nix/pull/115

**Comment by neosimsim** [comment]
Sorry, I forgot to check for existing issue before #115.

**Comment by TerrorJack** [comment]
Oh never mind! I just confirmed #115 is sufficient to resolve this issue.

**Comment by supersven** [comment]
I've merged the corresponding PR.
