### ISSUE TITLE
cabal: The program 'alex' could not be determined.

### ISSUE THREAD

**Issue by agander** [alpmestan/ghc.nix#13]
I dont know how to trace this error so I thought I would try here, as you helped me out on irc/ghc-dev, so my apologies if this should go elsewhere.
I completed the build and now I want to run the docs build, as thats where my focus is: [](https://ghc.haskell.org/trac/ghc/ticket/14475)
I have messed about with my configuration of nixos in a bid to understand how it works.

I had on reply on irc: (siarheit): "could it be your alex binary fails to start at all?"
But it made no sense.

Command was:
`nix-shell ./ghc.nix/  --run 'hadrian/build.sh --trace docs'`

Full message is:
Entering a GHC development shell with CFLAGS, CPPFLAGS, LDFLAGS and
LD_LIBRARY_PATH correctly set, to be picked up by ./configure.

    CC              = /nix/store/cg650dmmsy2bmsbx1y5f8qqpjb5hr0g2-gcc-wrapper-7.3.0/bin/cc
    CC_STAGE0       = /nix/store/cg650dmmsy2bmsbx1y5f8qqpjb5hr0g2-gcc-wrapper-7.3.0/bin/cc
    CFLAGS          = -I/nix/store/p9zl3jj7gzwn11h4w8n46w9ql3df31d3-ghc-build-environment/include
    CPPFLAGS        = -I/nix/store/p9zl3jj7gzwn11h4w8n46w9ql3df31d3-ghc-build-environment/include
    LDFLAGS         = -L/nix/store/p9zl3jj7gzwn11h4w8n46w9ql3df31d3-ghc-build-environment/lib
    LD_LIBRARY_PATH = /nix/store/p9zl3jj7gzwn11h4w8n46w9ql3df31d3-ghc-build-environment/lib
    LLVM            = NO
    libdw           = YES
    numa            = YES
    configure flags = --enable-dwarf-unwind

Please report bugs, problems or contributions to
https://github.com/alpmestan/ghc.nix
Resolving dependencies...
Build profile: -w ghc-8.2.2 -O1
In order, the following will be built (use -v for more details):
 - hadrian-0.1.0.0 (exe:hadrian) (configuration changed)
Configuring executable 'hadrian' for hadrian-0.1.0.0..
cabal: The program 'alex' version >=3.1 is required but the version of
/home/gander/.cabal/store/ghc-8.2.2/alex-3.2.4-8e59163a7521e7d29e8a27987d587ff2b6203aeb585fa79705d0c7a26f36ebac/bin/alex could not be determined.

I did:
`nix-shell ./ghc.nix/  --run 'alex --version'`
to get:
Alex version 3.2.4, (c) 2003 Chris Dornan and Simon Marlow

**Comment by alpmestan** [comment]
Interesting. I have absolutely no idea why Cabal cannot determine the version of `alex` there, and I've not seen this error myself.

Could you perhaps try removing `/home/gander/.cabal/store/ghc-8.2.2/alex-3.2.4-8e59163a7521e7d29e8a27987d587ff2b6203aeb585fa79705d0c7a26f36ebac` altogether? This should force cabal-install to get a new alex and build it, and hopefully it won't have any reason to complain about this one.

Note: it's a little odd that you get `hadrian-0.1.0.0 (exe:hadrian) (configuration changed)` (note the configuration changed bit), if you've already built and run hadrian before, unless you indeed have changed something (built it from another nix-shell?). This might be related to why you see this error, I think?

And yes, please do feel free to use this repo for those ghc/nix questions. :-)

**Comment by agander** [comment]
Thanks Alp.

Yes, I have zapped /nix: after building ghc successfully. (More than once)
I now see many of these while rebuilding hadrian: "[Base changed]".
re Zapping /nix:Is that going to cause me even more problems, I wonder.

Ok, alex problem is ok now.

**Comment by alpmestan** [comment]
You have zapped /nix? As in, removed it? Hmm, that might be problematic indeed =)
