### ISSUE TITLE
Provide LD to the environment

### ISSUE THREAD

**Issue by s-and-witch** [alpmestan/ghc.nix#133]
Both new `wasm` and `js` backends want `ld` into `hadrian/cfg/system.config` to be set upped. It can be done by providing LD environment variable to the configuration, but as I can see, you unset it: https://github.com/alpmestan/ghc.nix/blob/master/default.nix#L156
Is there some issue with this variable?

**Comment by Player-205** [comment]
JS backend uses `emscripten` for configuration and WASM has its own https://gitlab.haskell.org/ghc/ghc-wasm-meta
