### ISSUE TITLE
More stable nixpkgs sources

### ISSUE THREAD

**Issue by supersven** [alpmestan/ghc.nix#152]
Currently, `ghc.nix` seems to build "the whole world". (Even `tar` is compiled!) That's too time consuming and thus not good.

We should check, when we can remove the dependency on `nixpkgs-unstable`, again. (I guess that's the root cause.)

**Comment by bgamari** [comment]
Yes, I agree. We should, IMHO, keep `ghc.nix` on a nixos release branch (ideally the most recent release) if at all possible.

**Comment by MangoIV** [comment]
the next release of a stable package set will happen in may, I recommend to switch to stable then.

**Comment by MangoIV** [comment]
I've also looked at the latest actions, sometimes you just have an unlucky one. e.g. the last one took 1.5h and it seems like it spent most of the time building ghc, then last week there was one that took twice as long. This can be avoided with a stable package set but I think the three hours case was also particularly unlucky.

**Comment by MangoIV** [comment]
we can switch back to stable 2023-05-31 based on the [release schedule](https://github.com/NixOS/nixpkgs/issues/223562) for `nixos 23.05`.
