### ISSUE TITLE
Building GHC JS Backend fail: Missing C Library `gmp`

### ISSUE THREAD

**Issue by yvan-sraka** [alpmestan/ghc.nix#163]
Hello,

I'm attempting to build the GHC JavaScript backend, using zsh and nix-direnv, by following the instructions provided [here](https://gitlab.haskell.org/ghc/ghc/-/wikis/javascript-backend/building). However, I've encountered an error. Here's the sequence of commands I used for building:

```
./boot
./configure ${=CONFIGURE_ARGS}
emconfigure ./configure --target=javascript-unknown-ghcjs
hadrian/build -j12 --flavour=quick --bignum=native --docs=none
```

The error I encountered is as follows:

```
# cabal-configure (for _build/stage1/libraries/ghc-bignum/setup-config)
hadrian: Missing dependency on a foreign library:
* Missing (or bad) C library: gmp
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.If the
library file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.

ExitFailure 1
Build failed.
```

For reference, my `shell.nix` looks like this:

```nix
import ~/ghc.nix/shell.nix { # checkout on master
  withGhcid = true;
  withIde = true;
  withHadrianDeps = true;
  withEMSDK = true;
  #useClang = true; # I tried enabling/disabling ...
  #withLlvm = true; # ... both options
}
```

I'm planning to spend some time over the weekend trying to fix this issue myself. However, any guidance or suggestions you could offer in the meantime would be greatly appreciated.

Best, 
Yvan

**Comment by jappeace** [comment]
not sure, this is always pulled in as a system library: https://github.com/alpmestan/ghc.nix/blob/master/ghc.nix#L93
cabal can't find it for some reason :s

**Comment by hsyl20** [comment]
You shouldn't need
```
./configure ${=CONFIGURE_ARGS}
```

---

In theory hadrian with `--bignum=native` should enable the native backend that doesn't require GMP. But if you have leftover files from a previous build (especially `./_build/stage1/libraries/ghc-bignum/build/ghc-bignum.buildinfo`), it may fail.

**Comment by yvan-sraka** [comment]
```
rm ./_build/stage1/libraries/ghc-bignum/build/ghc-bignum.buildinfo
./boot
emconfigure ./configure --target=javascript-unknown-ghcjs
hadrian/build -j12 --flavour=quick --bignum=native --docs=none
```
Solve the issue :tada:! Thanks @hsyl20 :)

**Comment by yvan-sraka** [comment]
Follow-up issue https://gitlab.haskell.org/ghc/ghc/-/issues/23468 :)
