### ISSUE TITLE
The provided HLS (version 1.10) is unusable

### ISSUE THREAD

**Issue by sgraf812** [alpmestan/ghc.nix#184]
I noticed that recently (not sure since when, perhaps since ZuriHac in June) the HLS provided in this shell is unusably slow.

I've no idea what's going on and passing `--debug` to HLS doesn't provide any insight either.

I wonder if we could maybe switch to unstable's HLS? Perhaps that works better... Unfortunately, I couldn't get [it](https://github.com/sgraf812/ghc.nix/commit/16793a9b30b08240ca30538113d70a5145416ad9) to build locally.

**Comment by MangoIV** [comment]
you don't have to use the same package set for hls as we use for providing the other deps, you may use a different one; be careful that we do have to use the same compiler though, as the ABIs have to match.

**Comment by MangoIV** [comment]
oh it also seems as though the failure of your build doesn't even occur due to an actual build error but because the runner is killed, this may be because of too much consumed RAM; you might try to build locally instead and if it works, perhaps someone can push directly to the cachix, avoiding to build hls on the github runner...

**Comment by sgraf812** [comment]
> you don't have to use the same package set for hls as we use for providing the other deps, you may use a different one; be careful that we do have to use the same compiler though, as the ABIs have to match.

Yes, that's what I tried in the linked commit, I think.

> you might try to build locally instead and if it works

It didn't build locally, though, either, but I don't remember the details. I guess I can try again.

**Comment by MangoIV** [comment]
> Yes, that's what I tried in the linked commit, I think.

you changed hspkgs; that means that all other deps that come from hspkgs will also change.

**Comment by sgraf812** [comment]
Thanks, https://github.com/sgraf812/ghc.nix/commit/08ae02d4a801c4f3822710ecb0ce4a0da6d8da63 seems to build (locally at least) and I got HLS 2.1. I'll see if that makes a difference.

**Comment by sgraf812** [comment]
OK, I think the problem is with my editor's LSP plugin (https://github.com/kak-lsp/kak-lsp), not with HLS. It seems to work in VS code and doom emacs. Perhaps that is due to the version of kak-lsp that is in nixpkgs is 14.1.0 and not the most recent 14.2.0, which added support for `workspace/didChangeWatchedFiles` notifications. Sigh.

**Comment by MangoIV** [comment]
>  not the most recent 14.2.0

if you're lucky, you can just make flake that provides an overriden kakoune that has the correct version, you would `overrideAttrs` `src` and `version`...

**Comment by MangoIV** [comment]
so as a flake input provide the github of the upstream kakoune (or whatever version you like), add `flake = false` and will always be kept up to date if you update your flake :)
