### ISSUE TITLE
Can't run on macOS

### ISSUE THREAD

**Issue by int-index** [alpmestan/ghc.nix#22]
Running

```nix-shell https://github.com/alpmestan/ghc.nix/archive/master.tar.gz```

... fails with:

```
error: Package ‘numactl-2.0.12’ in /nix/store/rw2dcrqrgk9jnx7vbnc3rr4g1hccdpwi-nixpkgs-18.09pre150352.7c826371c49/nixpkgs/pkgs/os-specific/linux/numactl/default.nix:31 is not supported on ‘x86_64-apple-darwin’, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

**Comment by alpmestan** [comment]
@int-index Oh, indeed, hadn't thought of that. It should be enough to include `numactl` only when the system is not darwin. Would you like to write the patch or should I?

**Comment by int-index** [comment]
>  It should be enough to include numactl only when the system is not darwin.

Thanks! I'll try that.

> Would you like to write the patch or should I?

I will write the patch when I'm back home (in a couple of hours).

**Comment by int-index** [comment]
@alpmestan I've set `withNuma` and `withDwarf` to false, but it resulted in a different error:

```
$ nix-shell --show-trace
error: while evaluating the attribute 'LOCALE_ARCHIVES' of the derivation 'ghc-8.7' at /nix/store/rw2dcrqrgk9jnx7vbnc3rr4g1hccdpwi-nixpkgs-18.09pre150352.7c826371c49/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:179:11:
cannot coerce null to a string, at /Users/int-index/Projects/ghc.nix/default.nix:120:22
```

I tried to silence it by commenting out the definition of `LOCALE_ARCHIVES` and it resulted in yet another error:

```
$ nix-shell --show-trace
error: while evaluating the attribute 'shellHook' of the derivation 'ghc-8.7' at /nix/store/rw2dcrqrgk9jnx7vbnc3rr4g1hccdpwi-nixpkgs-18.09pre150352.7c826371c49/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:179:11:
while evaluating the attribute 'buildInputs' of the derivation 'src-1.18' at /nix/store/rw2dcrqrgk9jnx7vbnc3rr4g1hccdpwi-nixpkgs-18.09pre150352.7c826371c49/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:179:11:
while evaluating the attribute 'handled' at /nix/store/rw2dcrqrgk9jnx7vbnc3rr4g1hccdpwi-nixpkgs-18.09pre150352.7c826371c49/nixpkgs/pkgs/stdenv/generic/check-meta.nix:213:7:
while evaluating 'handleEvalIssue' at /nix/store/rw2dcrqrgk9jnx7vbnc3rr4g1hccdpwi-nixpkgs-18.09pre150352.7c826371c49/nixpkgs/pkgs/stdenv/generic/check-meta.nix:128:28, called from /nix/store/rw2dcrqrgk9jnx7vbnc3rr4g1hccdpwi-nixpkgs-18.09pre150352.7c826371c49/nixpkgs/pkgs/stdenv/generic/check-meta.nix:214:14:
Package ‘rcs-5.9.4’ in /nix/store/rw2dcrqrgk9jnx7vbnc3rr4g1hccdpwi-nixpkgs-18.09pre150352.7c826371c49/nixpkgs/pkgs/applications/version-management/rcs/default.nix:19 is not supported on ‘x86_64-apple-darwin’, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.
```

**Comment by alpmestan** [comment]
`rcs`? Hmmm... What's that, and what pulls it? Any chance you could look into this?

**Comment by supersven** [comment]
Hey,

I experience the same problem on my local machine (MacOS High Sierra):

Before commenting out `LOCALE_ARCHIVES`:

```
➜  ghc git:(master) nix-shell ghc.nix/ --show-trace

error: while evaluating the attribute 'LOCALE_ARCHIVES' of the derivation 'ghc-8.7' at /nix/store/pqrnxvm2mcv73cvaicvrwz1i385gl9pl-nixpkgs-18.09pre152619.7cb7d778300/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:177:11:
cannot coerce null to a string, at /Users/sventennie/src/ghc/ghc.nix/default.nix:119:22
```

After:

```
➜  ghc git:(master) nix-shell ghc.nix/ --show-trace

error: while evaluating the attribute 'shellHook' of the derivation 'ghc-8.7' at /nix/store/pqrnxvm2mcv73cvaicvrwz1i385gl9pl-nixpkgs-18.09pre152619.7cb7d778300/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:177:11:
while evaluating the attribute 'buildInputs' of the derivation 'src-1.18' at /nix/store/pqrnxvm2mcv73cvaicvrwz1i385gl9pl-nixpkgs-18.09pre152619.7cb7d778300/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:177:11:
while evaluating the attribute 'handled' at /nix/store/pqrnxvm2mcv73cvaicvrwz1i385gl9pl-nixpkgs-18.09pre152619.7cb7d778300/nixpkgs/pkgs/stdenv/generic/check-meta.nix:238:7:
while evaluating 'handleEvalIssue' at /nix/store/pqrnxvm2mcv73cvaicvrwz1i385gl9pl-nixpkgs-18.09pre152619.7cb7d778300/nixpkgs/pkgs/stdenv/generic/check-meta.nix:143:28, called from /nix/store/pqrnxvm2mcv73cvaicvrwz1i385gl9pl-nixpkgs-18.09pre152619.7cb7d778300/nixpkgs/pkgs/stdenv/generic/check-meta.nix:239:14:
Package ‘rcs-5.9.4’ in /nix/store/pqrnxvm2mcv73cvaicvrwz1i385gl9pl-nixpkgs-18.09pre152619.7cb7d778300/nixpkgs/pkgs/applications/version-management/rcs/default.nix:19 is not supported on ‘x86_64-apple-darwin’, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.
```

Please let me know, if I can help by trying something... 😃 

Best regards,

Sven

**Comment by alpmestan** [comment]
@supersven I'm sorry that I don't have a better suggestion, but do you think you could start commenting out some of the build inputs from [this list](), trying to enter the shell everytime you comment out one entry, until it succeeds? This way we'll know what pulls `rcs`. Regarding `LOCALE_ARCHIVES`, the fix is trivial, we can just set it when on linux.

**Comment by supersven** [comment]
Hey @alpmestan ,

Thanks for your fast response. Looks like the `buildInputs` of `default.nix` aren't the problem. I commented out all of it's entries but the problem still existed.

The offending line seems to be line 93: 
`    # export NIX_LDFLAGS+= " -rpath ${src}/inplace/lib/ghc-${version}"`

When I delete this line, the `nix-shell` starts as expected (without any error messages).

Maybe this line imports the package `src` (https://github.com/NixOS/nixpkgs/blob/6d6e4e6b558989246ba99d13ddbafb8744cdb0b6/pkgs/applications/version-management/src/default.nix#L26) which itself has `rcs` in `buildInputs`?

Best regards,

Sven

**Comment by alpmestan** [comment]
Oh dear, your suggestion is quite likely correct. Can you try #24?

**Comment by supersven** [comment]
Yes, of course :)

That branch works: `nix-shell` starts without errors.

**Comment by alpmestan** [comment]
Great. I'm leaving this issue open, feel free to close it once you're confident enough that the build environment works fine on OS X too, maybe after a few GHC builds etc. Merging the PR too.

**Comment by supersven** [comment]
Cool!

Sounds like a plan 👍

**Comment by alpmestan** [comment]
Hmmm, yeah, try adding llvm to the `env` thing in `default.nix`. I'm not quite sure what's going on but if that doesn't work I can look into it (e.g by looking up where that error message is emitted in GHC, to figure out how GHC detects LLVM).

**Comment by supersven** [comment]
I set `useClang`and `withLlvm`:
```
...
, useClang  ? true  # use Clang for C compilation
, withLlvm  ? true
...
```

As result, ghc unfortunately can not be built: https://gist.github.com/supersven/325aff7738bcce45813f1656e2a5ad8c

What looks notable on a first glimpse, is:

Line 97:
```
checking XCode version... ./configure: line 5220: xcodebuild: command not found
```

And many entries like:
```
[  1 of 270] Compiling Control.Monad.Cont.Class ( libraries/mtl/Control/Monad/Cont/Class
.hs, bootstrapping/Control/Monad/Cont/Class.o )                                        
You are using an unsupported version of LLVM!
Currently only 5.0 is supported.
We will try though...
```

The final error is:
```
Linking utils/ghc-cabal/dist/build/tmp/ghc-cabal ...
clang-5.0: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-
argument]                                                                              
clang-5.0: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-
argument]                                                                              
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _hs_iconv in libHSbase-4.11.1.0.a(iconv.o)
     (maybe you meant: _base_GHCziIOziEncodingziIconv_iconvEncoding1_info, _base_GHCziIO
ziEncodingziIconv_iconvEncoding3_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding4
_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding7_closure , _base_GHCziIOziEncodi
ngziIconv_iconvEncoding15_info , _base_GHCziIOziEncodingziIconv_iconvEncoding4_info , _b
ase_GHCziIOziEncodingziIconv_iconvEncoding7_info , _base_GHCziIOziEncodingziIconv_iconvE
ncoding6_closure , _hs_iconv , _base_GHCziIOziEncodingziIconv_iconvEncoding5_closure , _
base_GHCziIOziEncodingziIconv_iconvEncoding8_info , _hs_iconv_open , _base_GHCziIOziEnco
dingziIconv_iconvEncoding9_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding12_info
 , _base_GHCziIOziEncodingziIconv_iconvEncoding1_closure , _base_GHCziIOziEncodingziIcon
v_iconvEncoding6_info , _base_GHCziIOziEncodingziIconv_iconvEncoding14_bytes , _base_GHC
ziIOziEncodingziIconv_iconvEncoding8_closure , _base_GHCziIOziEncodingziIconv_iconvEncod
ing_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding10_bytes , _base_GHCziIOziEnco
dingziIconv_iconvEncoding2_info , _base_GHCziIOziEncodingziIconv_iconvEncoding13_info , 
_base_GHCziIOziEncodingziIconv_iconvEncoding2_closure , _hs_iconv_close , _base_GHCziIOz
iEncodingziIconv_iconvEncoding11_info , _base_GHCziIOziEncodingziIconv_iconvEncoding_inf
o , _base_GHCziIOziEncodingziIconv_iconvEncoding12_closure , _base_GHCziIOziEncodingziIc
onv_iconvEncoding11_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding15_closure , _
base_GHCziIOziEncodingziIconv_iconvEncoding13_closure , _base_GHCziIOziEncodingziIconv_i
convEncoding9_info )                                                                   
  "_iconv_open", referenced from:
      _hs_iconv_open in libHSbase-4.11.1.0.a(iconv.o)
     (maybe you meant: _hs_iconv_open)
  "_iconv_close", referenced from:
      _hs_iconv_close in libHSbase-4.11.1.0.a(iconv.o)
     (maybe you meant: _hs_iconv_close)
  "_locale_charset", referenced from:
      _localeEncoding in libHSbase-4.11.1.0.a(PrelIOUtils.o)
ld: symbol(s) not found for architecture x86_64
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
`cc' failed in phase `Linker'. (Exit code: 1)
utils/genprimopcode/ghc.mk:19: utils/genprimopcode/dist/package-data.mk: No such file or
 directory                                                                             
make[1]: *** [utils/ghc-cabal/ghc.mk:56: utils/ghc-cabal/dist/build/tmp/ghc-cabal] Error
 1                                                                                     
make: *** [Makefile:124: all] Error 2
```

I think as a next step, I'll try to explicitly use LLVM 5 and will try to figure out what's the matter with `xcodebuild`.

**Comment by int-index** [comment]
> The final error is:
> `_iconv <...>`

I think the fix for this is to add `libiconv` to `buildInputs`.

**Comment by alpmestan** [comment]
Yes, and whatever package xcodebuild is in on the darwin edition of nixpkgs, maybe? I don't know how important it is to detect it.

**Comment by supersven** [comment]
Hey,

Good news: I successfully built `master` with `nix-shell ghc.nix/ --pure --run './boot && ./configure && make -j12'`.

For that, I added `libiconv` and used `clang`:
```
...
, useClang  ? true  # use Clang for C compilation
...
  buildInputs = [ env arcanist libiconv ];
...
```

Thanks for giving that hint! I'll provide a patch regarding `libiconv` soon.

Next possible issue: The default compiler on MacOS seems to be `clang` (not gcc):
```
➜  ghc git:(master) nix repl "<nixpkgs>"
Welcome to Nix version 2.1.3. Type :? for help.

Loading '<nixpkgs>'...
Added 9402 variables.

nix-repl> cc.name
"clang-wrapper-5.0.2"

nix-repl> stdenv.cc.name
"clang-wrapper-5.0.2"
```

So this expression doesn't work:
```
    stdenv =
      if useClang
      then nixpkgs.clangStdenv
      else nixpkgs.stdenv;
```

Even if `useClang` is false, `clang` is used:

```
➜  ghc git:(master) nix-shell ghc.nix/ --pure --run './boot && ./configure && make -j12'
Entering a GHC development shell with CFLAGS, CPPFLAGS, LDFLAGS and
LD_LIBRARY_PATH correctly set, to be picked up by ./configure.

    CC              = /nix/store/2gdwhdzhy4iwkp7fh8v6gy6nxj1zi9pv-clang-wrapper-5.0.2/bin/cc
    CC_STAGE0       = /nix/store/2gdwhdzhy4iwkp7fh8v6gy6nxj1zi9pv-clang-wrapper-5.0.2/bin/cc
    CFLAGS          = -I/nix/store/xb3hjv7hsph1i8i9ihxgyif1ihbibbbz-ghc-build-environment/include
    CPPFLAGS        = -I/nix/store/xb3hjv7hsph1i8i9ihxgyif1ihbibbbz-ghc-build-environment/include
    LDFLAGS         = -L/nix/store/xb3hjv7hsph1i8i9ihxgyif1ihbibbbz-ghc-build-environment/lib
    LD_LIBRARY_PATH = /nix/store/xb3hjv7hsph1i8i9ihxgyif1ihbibbbz-ghc-build-environment/lib
    LLVM            = NO
    libdw           = NO
    numa            = NO
    configure flags =
...
```

If there's no better suggestion, I'll make an experiment with `gccStdenv` instead of `stdenv`.

Best regards,

Sven

**Comment by mpickering** [comment]
You should probably guard `libiconv` so that it's only a build dependency on darwin.

```
stdenv.lib.optionals stdenv.isDarwin [ libiconv ]
```

**Comment by int-index** [comment]
Here are some test failure that I'm experiencing on `macOS` with `ghc.nix`:

1. extra `ld` output messes with `stderr`:
```
cd "determinism/T13807/T13807.run" && $MAKE -s --no-print-directory T13807  
Actual stderr output differs from expected:
diff -uw "/dev/null" "determinism/T13807/T13807.run/T13807.run.stderr.normalised"
--- /dev/null	2019-02-13 23:19:47.222785000 +0300
+++ determinism/T13807/T13807.run/T13807.run.stderr.normalised	2019-02-13 23:19:51.343343577 +0300
@@ -0,0 +1,2 @@
+ld: warning: /nix/store/fxnlihrix22xsxqkrq8gd3n9ym625868-libiconv-osx-10.11.6/lib/libiconv.dylib, ignoring unexpected dylib file
+ld: warning: /nix/store/fxnlihrix22xsxqkrq8gd3n9ym625868-libiconv-osx-10.11.6/lib/libiconv.dylib, ignoring unexpected dylib file
*** unexpected failure for T13807(normal)
=====> driver016(normal) 2 of 49 [0, 1, 0]
cd "driver/driver016.run" && $MAKE -s --no-print-directory test016  
Actual stderr output differs from expected:
diff -uw "/dev/null" "driver/driver016.run/driver016.run.stderr.normalised"
--- /dev/null	2019-02-13 23:19:51.691743000 +0300
+++ driver/driver016.run/driver016.run.stderr.normalised	2019-02-13 23:19:53.256843189 +0300
@@ -0,0 +1 @@
+ld: warning: /nix/store/fxnlihrix22xsxqkrq8gd3n9ym625868-libiconv-osx-10.11.6/lib/libiconv.dylib, ignoring unexpected dylib file
*** unexpected failure for driver016(normal)
```
2. failure to link to `Foundation.c`:
```
=====> objc-hi(normal) 17 of 49 [0, 16, 0]
cd "driver/objc/objc-hi.run" &&  "/Users/int-index/Projects/ghc/inplace/bin/ghc-stage2" -o objc-hi objc-hi.m -dcore-lint -dstg-lint -dcmm-lint -no-user-package-db -rtsopts -fno-warn-missed-specialisations -fshow-warning-groups -fdiagnostics-color=never -fno-diagnostics-show-caret -Werror=compat -dno-debug-output  -framework Foundation -no-hs-main 
Compile failed (exit code 1) errors were:

objc-hi.m:1:9: error:
     fatal error: 'Foundation/Foundation.h' file not found
#import <Foundation/Foundation.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
`cc' failed in phase `C Compiler'. (Exit code: 1)

*** unexpected failure for objc-hi(normal)
```

**Comment by alpmestan** [comment]
Regarding 1), the `ld` warning, hmm... Do we only need to include iconv on Linux perhaps?

Regarding 2), I'm not sure what we should do... It seems the only reason for that error is `-framework Foundation`, which presumably comes from the test (it's an objective-C related test after all). I'm not sure exactly how/where that Foundation framework is supposed to be found. Perhaps you need to add some OSX-specific Nix packages to the environment and/or one of the env vars that are defined in `default.nix` ?

Regarding 3), I'm not sure I have a better thing to suggest than to try and strip down the environment's dependencies (conditionally, just when OS X) by removing anything that you don't actually need . Perhaps you can save a few entries this way and get the argument list to be short enough again. This is a known problem, I don't quite remember the best ways to work around it, maybe @angerman does?

**Comment by int-index** [comment]
> Regarding 1), the `ld` warning, hmm... Do we only need to include iconv on Linux perhaps?

No. On the contrary, we only include it on Darwin, see #28

> Regarding 2), <...> Perhaps you need to add some OSX-specific Nix packages to the environment and/or one of the env vars that are defined in `default.nix` ?

Yes, this worked! #33 

> Regarding 3) I'm not sure I have a better thing to suggest than to try and strip down the environment's dependencies (conditionally, just when OS X) by removing anything that you don't actually need

The test itself generates 10k -optP arguments by design. It is disabled on Windows:

```
test('T14697',
     [ collect_compiler_stats('bytes allocated',10),
       # This generates too large of a command-line for poor Windows
       when(opsys('mingw32'), expect_broken(15072)),
       pre_cmd('./genT14697'),
       extra_files(['genT14697']),
       extra_hc_opts('$(cat T14697-flags)'), # 10k -optP arguments
     ],
     multimod_compile,
     ['T14697', '-v0'])
```

I could disable it on Darwin, too, but this begs the question: how come GitLab CI passes? I wouldn't expect this to be Nix-specific...

**Comment by angerman** [comment]
> I could disable it on Darwin, too, but this begs the question: how come GitLab CI passes? I wouldn't expect this to be Nix-specific...

GitLab doesn't use nix, and as such doesn't suffer from the excessive environment pollution nix does. It also does not necessarily suffer from the long store paths that nix uses.

Thus, this could very well be a nix issue.

**Comment by alpmestan** [comment]
@int-index Thanks for #33! I merged it.

Regarding T14697, I suspect @angerman is on the right track, and I'm not sure how best to solve this. Do let me know if there's anything we can add to ghc.nix to help with that.

**Comment by int-index** [comment]
T14697 started to fail on GitLab CI too, so I disabled it. The remaining issue is the extra `ld` output. I suspect it might have something to do with macOS version:

```
+ld: warning: /nix/store/fxnlihrix22xsxqkrq8gd3n9ym625868-libiconv-osx-10.11.6/lib/libiconv.dylib, ignoring unexpected dylib file
```

My system is not 10.11.6, it is 10.14.2

Not sure what to do about it.

**Comment by alpmestan** [comment]
I haven't used nix on OS X since the early days of darwin support. I don't have the slightest clue about why it pcks that OSX version, perhaps this is something you could ask on #nixos, nixpkgs' issue tracker or the discourse thingie?

**Comment by int-index** [comment]
Yes, at this point it's probably out of scope of `ghc.nix`.

**Comment by alpmestan** [comment]
Well, if there's a solution, I'm sure it'll require changing ghc.nix, but chasing that solution down is not something I can personally help with. I'll be glad to merge any patch that fixes this though :)

**Comment by Ericson2314** [comment]
Doesn't this work now?

**Comment by int-index** [comment]
The original issue is fixed but extra `ld` output is not.
