### ISSUE TITLE
Issues with LOCALE settings.

### ISSUE THREAD

**Issue by AndreasPK** [alpmestan/ghc.nix#25]
Using `nix-shell ~/ghc.nix` I get locale errors from perl during tests:

```
+perl: warning: Setting locale failed.
+perl: warning: Please check that your locale settings:
+       LANGUAGE = (unset),
+       LC_ALL = "en_US.utf8",
+       LANG = "en_US.utf8"
+    are supported and installed on your system.
+perl: warning: Falling back to the standard locale ("C").
*** unexpected failure for hpc001(normal)
```

I found a workaround using `nix-shell ~/ghc.nix -p glibcLocales` however that's bothersome to remember. Adding glibcLocales to the dep list for whatever reason doesn't work only the shell invocation does.

Could you add this behaviour to the nix expression?

**Comment by int-index** [comment]
Does it help if you change

```
LOCALE_ARCHIVES = 
```

to

```
LOCALE_ARCHIVE = 
```

in `ghc.nix`?

**Comment by AndreasPK** [comment]
Yes that seems to do it.

**Comment by alpmestan** [comment]
Oh dear. My apologies =)

**Comment by alpmestan** [comment]
Fixed in https://github.com/alpmestan/ghc.nix/commit/83dd1adc0ab84f3b91361fc73bd564865491dff8.
