### ISSUE TITLE
cabal: Could not resolve dependencies: [__1] rejecting: hadrian-0.1.0.0 (conflict: Cabal==2.3.0.0, hadrian => Cabal>=2.5 && <2.6)

### ISSUE THREAD

**Issue by agander** [alpmestan/ghc.nix#29]
Hello,

Whilst running this:
nix-shell ./ghc.nix/        --run 'hadrian/build.sh -c -j4 --flavour=quickest' from within ghc/, I got the following:

Entering a GHC development shell with CFLAGS, CPPFLAGS, LDFLAGS and
LD_LIBRARY_PATH correctly set, to be picked up by ./configure.

    CC              = /nix/store/lzh9rcw3rjvbaj7n3z4nzsvcz85k2p2m-gcc-wrapper-7.3.0/bin/cc
    CC_STAGE0       = /nix/store/lzh9rcw3rjvbaj7n3z4nzsvcz85k2p2m-gcc-wrapper-7.3.0/bin/cc
    CFLAGS          = -I/nix/store/c7f4wxaa1a5x1zq1x7w6q2nqmxacvfpi-ghc-build-environment/include
    CPPFLAGS        = -I/nix/store/c7f4wxaa1a5x1zq1x7w6q2nqmxacvfpi-ghc-build-environment/include
    LDFLAGS         = -L/nix/store/c7f4wxaa1a5x1zq1x7w6q2nqmxacvfpi-ghc-build-environment/lib
    LD_LIBRARY_PATH = /nix/store/c7f4wxaa1a5x1zq1x7w6q2nqmxacvfpi-ghc-build-environment/lib
    LLVM            = NO
    libdw           = YES
    numa            = YES
    configure flags = --enable-dwarf-unwind

Please report bugs, problems or contributions to
https://github.com/alpmestan/ghc.nix
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] next goal: Cabal (user goal)
[__0] rejecting: Cabal-2.4.1.0, Cabal-2.4.0.1, Cabal-2.4.0.0 (constraint from
user target requires ==2.3.0.0)
[__0] trying: Cabal-2.3.0.0
[__1] next goal: hadrian (user goal)
[__1] rejecting: hadrian-0.1.0.0 (conflict: Cabal==2.3.0.0, hadrian =>
Cabal>=2.5 && <2.6)
[__1] fail (backjumping, conflict set: Cabal, hadrian)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: Cabal, hadrian

**Comment by agander** [comment]
Is this related to the message on ghc-devs, 3 Dec 2018, titled: "Cabal not updated after rebase?"

**Comment by mpickering** [comment]
You probably don't have a clean GHC tree. Make sure you run `git submodule update`.

**Comment by agander** [comment]
Thanks
