### ISSUE TITLE
Hadrian instructions don't work

### ISSUE THREAD

**Issue by vaibhavsagar** [alpmestan/ghc.nix#32]
I'm trying to follow the instructions in the README. I cloned this repo to `~/repos/ghc` and successfully ran `./boot && ./configure`, but this is what I get when I try to build with Hadrian:

```shell
[nix-shell:~/repos/ghc]$ hadrian/build.sh -j4 --flavour=quickest --build-root=_mybuild
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal                                                          
update' to download it.
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: hadrian-0.1.0.0 (user goal) 
[__1] unknown package: hadrian:happy:exe.happy (dependency of hadrian)
[__1] fail (backjumping, conflict set: hadrian, hadrian:happy:exe.happy)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: hadrian, hadrian:happy:exe.happy
```

Is there something I'm missing?

**Comment by mpickering** [comment]
Like the instructions say, it seems that you need to run `cabal update`.

**Comment by vaibhavsagar** [comment]
Hmm, where does it say that?

> You can alternatively use Hadrian to build GHC:
> ```
> $ nix-shell ~/ghc.nix/
> # from the nix shell:
> $ ./boot && ./configure
> # example hadrian command: use 4 cores, build a 'quickest' flavoured GHC
> # and place all the build artifacts under ./_mybuild/.
> $ hadrian/build.sh -j4 --flavour=quickest --build-root=_mybuild
> # you could also ask hadrian to boot and configure for you, with -c
> ```

**Comment by vaibhavsagar** [comment]
Ah, you mean in the error message. Can this be added to the instructions? My expectation is that I am able to follow the instructions in the README and get a freshly compiled GHC, which does not seem to be the case at the moment.

**Comment by alpmestan** [comment]
I indeed forgot about the implicit assumption that cabal-install has been used before, and that therefore it has a copy of hackage's index, for figuring out what versions of what are available.

Fixed in https://github.com/alpmestan/ghc.nix/commit/0c72c94120ae6db64520275c5893bded16cee87e.

**Comment by vaibhavsagar** [comment]
Thanks!
