### ISSUE TITLE
Add ghcid

### ISSUE THREAD

**Issue by transitracer** [alpmestan/ghc.nix#48]
ghcid is a tremendously useful tool for haskell development, and with it working on ghc now, it seems like a good idea to add it to ghc.nix

**Comment by alpmestan** [comment]
Sure, you can do like Matthew did for the last PR that I merged, the one that adds ghcide: just make it opt-in by having a `withGhcid` boolean argument for `default.nix`.

**Comment by supersven** [comment]
@transitracer , @alpmestan ,

I can offer to implement this (should be only a few changes). But I don't want to "steal" someones task ...

So, if you could need help with this task, just drop me a line ... :smiley:
