### ISSUE TITLE
Upgrade default GHC version

### ISSUE THREAD

**Issue by Sir4ur0n** [alpmestan/ghc.nix#64]
Hi,

I just tested today the following:
```shell
$ git clone --recursive git@gitlab.haskell.org:ghc/ghc.git
$ cd ghc/
$ git clone https://github.com/alpmestan/ghc.nix
$ nix-shell ghc.nix
$ ./boot
$ ./configure 
```

The last step (`./configure`) fails as such:
```
checking for gfind... no
checking for find... /nix/store/xhdbfv3kivss6y04xk9i4a5pknaww1az-findutils-4.7.0/bin/find
checking for sort... /nix/store/3kqc2wmvf1jkqb2jmcm7rvd9lf4345ra-coreutils-8.31/bin/sort
checking for GHC version date... inferred 8.11.0.20200331
checking for GHC Git commit id... inferred 4b9c586472bf99425f7bbcf346472d7c54f05028
checking for ghc... /nix/store/hcrblsvvbmamb2lwsv68n87dvncr6pq3-ghc-8.6.5/bin/ghc
checking version of ghc... 8.6.5
configure: error: GHC version 8.8 or later is required to compile GHC.
```

I think the default version of GHC should be upgraded to GHC 8.8 or more, what do you think?

Cheers!

Note: This seems to require an update of `nixpkgs.src-json` which is done using `nix/update-pin.sh nixpkgs HEAD` or `nix/update-pin.sh nixpkgs be0d1dc5a6c42456dbddde9b347d49cfaad034ef` if I'm not mistaken?

**Comment by supersven** [comment]
I think this will break the `ghcide` integration (arg: `withIde = true;`).

- https://github.com/cachix/ghcide-nix/blob/f940ec611cc6914693874ee5e024eba921cab19e/nix/default.nix#L28
- https://github.com/cachix/ghcide-nix/issues/3

But, well, if GHC can not be built any more... That's way more important 😃

**Comment by alpmestan** [comment]
@Sir4ur0n Correct, I remember seeing a GHC patch bumping the boot GHC requirement to 8.8, very very recently. I'm currently working in some branches that I haven't rebased so I have not run into the problem yet, but I would be happy to take a patch that sorts it all out. :-)

And indeed, just being able to work on GHC (without the IDE stuffs) is the most important part mission of this little nix environment, so I agree that any optional feature can be sorted out later.
