### ISSUE TITLE
Re-enable ghcide

### ISSUE THREAD

**Issue by supersven** [alpmestan/ghc.nix#73]
Looks like `ghcide-nix` now supports GHC 8.8.3. (I haven't tested it, yet, but the related branch was pushed to master this morning.)

That means we can revert the related changes from https://github.com/alpmestan/ghc.nix/pull/65.

**Comment by zeta-00** [comment]
@supersven , sounds good, let me know when the changes have been made, i can't wait to see ghcide up in running again in ghc.nix.

**Comment by bgamari** [comment]
It would be good to confirm whether `ghcide-nix` currently uses the `hls` branch as this is what @mpickering recommends.

**Comment by mpickering** [comment]
Yes, this won't work. You need the `hls` branch.

**Comment by supersven** [comment]
Okay, I didn't know that. In fact I'm using @mpickering s fork/branch ... :smiley:

**Comment by zeta-00** [comment]
@supersven  , hello again, just wondering if you guys have made any progress with this issue? also, will switching to the `hls branch` cause some issues?

**Comment by zeta-00** [comment]
oh, it's been fixed, i just finished building ghc and ghcide is up and running, thanks for fixing this.

**Comment by zeta-00** [comment]
i haven't tested ghcide with ghc yet, i still need to set it up with my (lorri+direnv+emacs-direnv) setup. let me know if any of you were able to get your lorri setup working with ghc.nix.
